name: pull-request

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install root dependencies
        run: yarn
      - name: Run root mocha tests
        run: yarn mocha ./tests
      - name: Install public dependencies
        working-directory: ./public
        run: yarn
      - name: Run public jest tests
        working-directory: ./public
        run: yarn jest ./src/tests
